"""
MemMini OpenClaw Adapter

OpenClaw MEMORY.md ↔ MemMini 양방향 동기화.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from memmini.adapters.base import MemoryAdapter
from memmini.core.memory_core import MemoryCore
from memmini.storage.file import FileStorage


class OpenClawAdapter(MemoryAdapter):
    """OpenClaw MEMORY.md 통합 어댑터

    OpenClaw 워크스페이스의 MEMORY.md 파일과 MemMini를
    양방향으로 동기화합니다.

    Examples:
        >>> adapter = OpenClawAdapter(
        ...     workspace_path="~/.openclaw/workspace"
        ... )
        >>> context = adapter.load_context(layers=["L0"])
        >>> adapter.save_memory("새 기억")
    """

    def __init__(
        self,
        workspace_path: str,
        memory_file: str = "MEMORY.md",
        auto_sync: bool = True,
    ):
        """OpenClawAdapter 초기화

        Args:
            workspace_path: OpenClaw 워크스페이스 경로
            memory_file: 메모리 파일명 (기본 MEMORY.md)
            auto_sync: 자동 동기화 여부
        """
        self.workspace = Path(workspace_path).expanduser()
        self.workspace.mkdir(parents=True, exist_ok=True)

        self.memory_file = self.workspace / memory_file
        self.auto_sync = auto_sync

        # MemMini 저장소 및 코어 초기화
        memmini_path = self.workspace / ".memmini"
        storage = FileStorage(base_path=str(memmini_path))
        core = MemoryCore(storage=storage, auto_layer_update=False)

        super().__init__(core)

    def load_context(self, layers: List[str]) -> Dict[str, str]:
        """OpenClaw 컨텍스트 로드

        지정된 계층의 메모리를 로드합니다.

        Args:
            layers: 로드할 계층 리스트 (["L0"], ["L0", "L1"] 등)

        Returns:
            계층별 내용 딕셔너리 {"L0": "...", "L1": "..."}

        Examples:
            >>> ctx = adapter.load_context(layers=["L0"])
            >>> print(ctx["L0"])
        """
        context = {}
        for layer in layers:
            content = self.core.retrieve(layer=layer)
            context[layer] = content
        return context

    def save_memory(self, content: str, metadata: Optional[Dict] = None) -> str:
        """메모리 추가 + MEMORY.md 동기화

        Args:
            content: 메모리 내용
            metadata: 메타데이터

        Returns:
            memory_id
        """
        memory_id = self.core.add(content, metadata)

        # 레이어 업데이트
        self.core.update_layers()

        if self.auto_sync:
            self.sync_to_platform()

        return memory_id

    def sync_to_platform(self) -> None:
        """MemMini → MEMORY.md 동기화

        L1 내용을 MEMORY.md 파일에 저장합니다.
        """
        l1_content = self.core.retrieve(layer="L1")

        with open(self.memory_file, "w", encoding="utf-8") as f:
            f.write("# MEMORY.md (Generated by MemMini)\n\n")
            f.write(f"_Last updated: {datetime.now().isoformat()}_\n\n")
            f.write(l1_content)

    def sync_from_platform(self) -> None:
        """MEMORY.md → MemMini 동기화

        기존 MEMORY.md 내용을 MemMini에 추가합니다.
        """
        if not self.memory_file.exists():
            return

        with open(self.memory_file, "r", encoding="utf-8") as f:
            content = f.read()

        if content.strip():
            self.core.add(
                content,
                metadata={
                    "source": "MEMORY.md",
                    "synced_at": datetime.now().isoformat(),
                },
            )

    def get_platform_object(self) -> Any:
        """OpenClaw 네이티브 객체 반환

        Returns:
            self (OpenClawAdapter 자체가 인터페이스)
        """
        return self
